### PR TITLE
ui: show an overlay with the list plugs with their respective icons

### PR DESCRIPTION
**Pull request by soumyaDghosh**
@aleixpol So, till now I have achieved the backend completely. I have added methods to expose the snaps, their names, plugs, slots etc. I have also added methods to connect and disconnect plugs. But, the overlay isn't still showing up. I haven't been able to impletement it. Kind of stuck there. Can you suggest me, how can I implement it? Also, the list isn't looking that great. Can you kindly give some suggestions on that front also?

### CODE REVIEW

**Comment by ScarlettGatelyMoore** [comment]
@AleixPol

**Comment by aleixpol** [comment]
snapd seems to be broken in archlinux so I can't test it. If it's not working I'd suggest you break down the problem into smaller parts until you start getting feedback.

What do you exactly mean by the overlay isn't showing? If you mean the OverlaySheet, here's some ideas:
- see that there aren't any qml warnings.
- make the parent root?
- try using a Kirigami.Dialog instead?

**Comment by soumyaDghosh** [comment]
Hii @aleixpol thanks a lot for taking your time. I actually got this working before UbuCon Asia and showcased this to Till and some others during UbuCon Asia. The overlay wasn't showing up back then, because I was running it using `kcmshell6` and the window size was small. I'll try to fix that. I got a lot of help from redstrate and nate from the KDE Development channel. This is the current state.

[Screencast_20240912_190035.webm](https://github.com/user-attachments/assets/38caf5d9-c41e-4378-b80a-b30f44c9351c)


I still have some questions, if you can please guide me a bit

1. Can I somehow assign the icons of the IconTitleSubtitle widget using QVariant variables? I'll have `QUrl` and `QImage` returned as `QVariant`. Because everytime I got this error, when I tried to

```bash
Unable to assign QImage to IconPropertiesGroup_QMLTYPE_67*
```

2. Is it possible to have a widget which has both Tiltle, Subtitle and Switches? Like a combo of `TiltleSubtitle` and `SwitchDelegate`. Probably I'll have to create a custom widget right?

3. Can you suggest me some UI ideas by which I can improve the design of this page?

**Comment by soumyaDghosh** [comment]
Hii @aleixpol I am going to merge this PR now, as I believe my project is completely ready. This is how the complete thing works rn.

[Screencast_20240915_020545.webm](https://github.com/user-attachments/assets/8d07872f-a917-43ee-a612-d1d466d93a77)


I have learnt some new things about the API which I'll try to implement in discover also. I believe I have the most efficient way to fetch the icons for snaps. One can also launch the snaps from this page. The search also works perfectly(may be needs some improve, it just filters the names rn, no fuzzy search ig). Now we'd need a debian package for this. I don't know much about packaging in debian. But I'll try. I am sure @ScarlettGatelyMoore will be able to help me with that!

Thanks a lot for all of your help!

**Comment by aleixpol** [comment]
I'd suggest you use a new page there instead of a dialog. It will look a bit cleaner. You could aim to replicate the flatpak kcm.

Also I don't understand why this isn't in invent.kde.org.

**Comment by soumyaDghosh** [comment]
I'll look into the new page. I thought that this would look nice. I actually didn't like the flatpak design much. But sure, thanks a lot for the suggestion. Also, I was waiting for the license to select. I've selected `GPL-2.0-or-later` for C++ and `BSD-Clause` for the qmls. This is now in kde invent. 

https://invent.kde.org/soumyadghosh/snap-kcm

**Comment by aleixpol** [comment]
There's no reason to use different licences on C++ and QML files, I suggest using the same (GPL?) for all.

**Pull request merged**
